abstract: An object-oriented interface to Musepack file information
author: 'Dan Sully, <daniel@cpan.org>'
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Audio-Musepack
no_index:
  directory:
    - inc
    - t
requires:
  MP3::Info: 1.20
  perl: 5.005
version: 0.6
